### ISSUE TITLE
UniGrid returns the wrong type

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/InducingPoints.jl#15]
The implementation of `UniGrid` is wrong at the moment it should return a smart matrix object but just returns a vector of range right now

**Comment by Crown421** [comment]
I would be very interested in fixing this, but I am not fully sure what you mean by "smart matrix object". 

Personally, I have been trying to get an `Iterator.product` to work, but this results in an iterator over tuples, which is not compatible with `ApproximateGPs`. 

Would it be acceptable to implement a `collect.(collect(Iterator.product(Z...)` construct for now, to bring `UniGrid` in line with the other methods?

**Comment by theogf** [comment]
So the idea is that each algorithm returns a `Vector` of `Vector` eventually as a wrapper. What I thought about as a smart matrix was to use some kind of Kronecker product structure and wrap it in `ColVecs` or something like this

**Comment by Crown421** [comment]
I think #31 closes this.
