### ISSUE TITLE
Combining `initZ` and `inducingpoints`

### ISSUE THREAD

**Issue by Crown421** [JuliaGaussianProcesses/InducingPoints.jl#23]
I am currently dipping my toes into this package, and I noticed that it is a bit jarring to use different functions got generate an array of inducing points `Z`.
This is especially noteable for the uniform grid `UniGrid`, which could also be used as a offline selection for inducing points. 

I saw the other issue with `UniGrid` (#15), which I am also thinking about. 

Is there perhaps a way to streamline the functions?

**Comment by theogf** [comment]
I guess these two could eventually be merged, they technically do the same thing after all
