### ISSUE TITLE
Let `UniGrid` have different number of point for each dimension

### ISSUE THREAD

**Issue by Crown421** [JuliaGaussianProcesses/InducingPoints.jl#30]
This is hopefully fairly simple, but adding it here to remember it later. 

I would be good if one could (optionally) set different a different number of points for each dimension in `UniGrid`, to faciliate e.g. non-square equidistant grids.

**Comment by theogf** [comment]
You actually solved this @Crown421 no?

**Comment by Crown421** [comment]
Oh yeah, I did :smile:
