### ISSUE TITLE
kernel as kwarg or part of struct

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/InducingPoints.jl#39]
There appear to be two ways to pass a kernel to `inducingpoints`, either as a field of `alg` or as a `kwarg` to `inducingpoints`. Should we choose a single canonical way to do this?

**Comment by theogf** [comment]
Ups you're right. I would be of the opinion that it should always be a `kwarg` but `StdDPP` and `kDPP` don't respect that...
